# Forked from eKatchko/public-bioinformatics-databases

name: Process changed files

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'
    paths:
      - 'databases/**.json'
  workflow_dispatch:
    inputs:
      base:
        type: string
        required: true
      head:
        type: string
        required: true
    
    
jobs:
  # This workflow contains a single job called "changed-files"
  changed-files:
    # The type of runner that the job will run on
    runs-on: [self-hosted, fts3]
    environment: APPROVAL_REQUIRED

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v16
        with:
          since_last_remote_commit: "true"
          files: |
            databases/*.json
            
      - name: Get changed files with git diff and send to fts3-connector
        id: git-diff
        run: |
          declare -a CHANGED=($(git diff --name-only -r origin/${{ github.base_ref || github.event.inputs.base }} origin/${{ github.head_ref || github.event.inputs.head }} | grep databases/**))
          for file in "${CHANGED[@]}"; do
            echo "Calling with $file"
            curl -H "X-AUTH-HEADER: ${{ secrets.FTS3_CLIENT_API_KEY }}" -H "Content-Type: application/json" -X POST -d @$file "${{ vars.FTS3_CLIENT_ENDPOINT }}/transfer/dry"
          done
